export const data = [
	{
		id: 0,
		src: './images/icons/menu/user_tonality_active.svg',
		text: 'Тональный ландшафт',
		path: '/user-tonality',
	},
	{
		id: 1,
		src: './images/icons/menu/information_graph_active.svg',
		text: 'Граф информации',
		// text: 'Информационный граф',
		path: '/information-graf',
	},
	{
		id: 2,
		src: './images/icons/menu/media_rating_active.svg',
		// text: 'СМИ',
		text: 'Медиа рейтинг',
		path: '/media-rating',
	},
	{
		id: 3,
		src: './images/icons/menu/voice_of_customer_active.svg',
		text: 'Голос клиента',
		path: '/voice-of-customer',
	},
	{
		id: 4,
		src: './images/icons/menu/competitive_environment_active.svg',
		text: 'Конкуренты',
		path: '/competitive',
	},
	{
		id: 5,
		src: './images/icons/menu/external_factors_active.svg',
		text: 'Внешние факторы',
		path: '/user-tonality',
	},
	{
		id: 6,
		src: './images/icons/menu/show_data_active.svg',
		text: 'Набор данных',
		path: '/data-set',
	},
	{
		id: 7,
		src: './images/icons/menu/authors_clastarization_active.svg',
		text: 'Кластеризация авторов',
		path: '/clustering',
	},
	// {
	// 	id: 8,
	// 	src: './images/icons/menu/text_classification_active.svg',
	// 	text: 'Text classification',
	// 	path: '/user-tonality',
	// },
	{
		id: 8,
		src: './images/icons/menu/table.png',
		text: 'Анализ тематик',
		path: '/topic-analysis',
	},
	{
		id: 9,
		src: './images/icons/menu/AI.png',
		text: 'ИИ анализ',
		path: '/ai-analytics',
	},
];
