export const menuPageData = [
	{
		id: 0,
		title: 'User tonality',
		src: '../images/icons/menu/user_tonality.svg',
		src_active: '../images/icons/menu/user_tonality_active.svg',
		path: '/user-tonality',
	},
	{
		id: 1,
		title: 'Information graph',
		src: '../images/icons/menu/information_graph.svg',
		src_active: '../images/icons/menu/information_graph_active.svg',
		path: '/information-graf',
	},
	{
		id: 2,
		title: 'Media rating',
		src: '../images/icons/menu/media_rating.svg',
		src_active: '../images/icons/menu/media_rating_active.svg',
		path: '/media-rating',
	},
	{
		id: 3,
		title: 'Voice of customer',
		src: '../images/icons/menu/voice_of_customer.svg',
		src_active: '../images/icons/menu/voice_of_customer_active.svg',
		path: '/voice-of-customer',
	},
	{
		id: 4,
		title: 'Competitive environment',
		src: '../images/icons/menu/competitive_environment.svg',
		src_active: '../images/icons/menu/competitive_environment_active.svg',
		path: '/none',
	},
	{
		id: 5,
		title: 'External factors',
		src: '../images/icons/menu/external_factors.svg',
		src_active: '../images/icons/menu/external_factors_active.svg',
		path: '/none',
	},
	{
		id: 6,
		title: 'Show data',
		src: '../images/icons/menu/show_data.svg',
		src_active: '../images/icons/menu/show_data_active.svg',
		path: '/none',
	},
	{
		id: 7,
		title: 'Authors clastarization',
		src: '../images/icons/menu/authors_clastarization.svg',
		src_active: '../images/icons/menu/authors_clastarization_active.svg',
		path: '/none',
	},
	{
		id: 8,
		title: 'Text classification',
		src: '../images/icons/menu/text_classification.svg',
		src_active: '../images/icons/menu/text_classification_active.svg',
		path: '/none',
	},
	{
		id: 9,
		title: 'Topic analysis',
		src: '../images/icons/menu/table.png',
		src_active: '../images/icons/menu/table.png',
		path: '/topic-analysis',
	},
	{
		id: 10,
		title: 'AI analytics',
		src: '../images/icons/menu/AI.png',
		src_active: '../images/icons/menu/AI.png',
		path: '/ai-analytics',
	},
];

export const menuSettings = [
	{
		id: 0,
		title: 'FAQ',
		src: '../images/icons/menu/FAQ.svg',
		src_active: '../images/icons/menu/FAQ_active.svg',
		path: '/faq',
	},
	{
		id: 1,
		title: 'Свернуть меню',
		src: '../images/icons/menu/change_menu.svg',
		src_active: '../images/icons/menu/change_menu.svg',
	},
	{
		id: 2,
		title: 'Выйти из аккаунта',
		src: '../images/icons/menu/logout.svg',
		src_active: '../images/icons/menu/logout.svg',
	},
];
